### ISSUE TITLE
energy: stromaustauschsaldo problem

### ISSUE THREAD

**Issue by aeschi** [uclab-potsdam/klimataz#443]
<img width="412" alt="Screenshot 2022-10-14 at 11 02 07" src="https://user-images.githubusercontent.com/56318362/196201327-af48f414-ca89-46d5-9579-4ef51c9298ee.png">

**Comment by johannahaha** [comment]
I think this might be Stromaustauschsaldo. Stromaustauschsaldo is sometimes negative . At one point we discussed removing this value from the energies because of this problem.

https://ag-energiebilanzen.de/faq/definitionen-methodik/ : Der Stromaustauschsaldo ist die Differenz des physikalischen Stromflusses aus dem Ausland nach Deutschland bzw. aus Deutschland ins Ausland.

**Comment by aeschi** [comment]
Stromaustauschsaldo raus aus Grafik, aber als Footnote in der Grafik.
